/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shoeshopmng;

import java.awt.HeadlessException;
import java.nio.charset.StandardCharsets;
import java.security.spec.KeySpec;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Base64;
import java.util.Random;
import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.PBEKeySpec;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author hdoff
 */
public class Login1 extends javax.swing.JFrame {

    /**
     * Creates new form Login1
     */
    private static final String SECRET_KEY = "123456789";
    private static final String SALTVALUE = "abcdefg";
    int k = 0;
    String OTP = null;
    String auid;

    public Login1() {
        initComponents();
        setupInitialUI();
    }

    public Login1(boolean fromBilling) {
        initComponents();
        setupInitialUI();
    }

    private void setupInitialUI() {
        loginbtn.setVisible(false);
        otplbl.setVisible(false);
        pnt1lbl.setVisible(false);
        otpnumlbl.setVisible(false);
        otptb.setEditable(false);
        otptb.setText("");
        auid = "";
    } 

    /**
     * This method is called from within the constructor to initialize the
     * form.WARNING: Do NOT modify this code.The content of this method is
     * always regenerated by the Form Editor.
     *
     * @param strToEncrypt
     * @return
     */
    public static String encrypt(String strToEncrypt) {
        try {
            byte[] iv = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
            IvParameterSpec ivspec = new IvParameterSpec(iv);
            /* Create factory for secret keys. */
            SecretKeyFactory factory = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256");
            /* PBEKeySpec class implements KeySpec interface. */
            KeySpec spec = new PBEKeySpec(SECRET_KEY.toCharArray(), SALTVALUE.getBytes(), 65536, 256);
            SecretKey tmp = factory.generateSecret(spec);
            SecretKeySpec secretKey = new SecretKeySpec(tmp.getEncoded(), "AES");
            Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5Padding");
            cipher.init(Cipher.ENCRYPT_MODE, secretKey, ivspec);
            /* Retruns encrypted value. */
            return Base64.getEncoder()
                    .encodeToString(cipher.doFinal(strToEncrypt.getBytes(StandardCharsets.UTF_8)));
        } catch (Exception e) {

        }
        return null;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cb = new javax.swing.JComboBox<>();
        otptb = new javax.swing.JTextField();
        otp = new javax.swing.JLabel();
        pnt1lbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pntlbl = new javax.swing.JLabel();
        otplbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        otpnumlbl = new javax.swing.JLabel();
        uid = new javax.swing.JTextField();
        verifybtn = new javax.swing.JButton();
        pswd = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        loginbtn = new javax.swing.JButton();
        resetbtn = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 5));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 35)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 255));
        jLabel11.setText("Login Page");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(212, 212, 212))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 8));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Best Price");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("Large Stock");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Good Facility");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("Quality ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("Trust Worthy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(13, 13, 13))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel10)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel7)
                .addGap(88, 88, 88)
                .addComponent(jLabel4)
                .addGap(83, 83, 83)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(85, 85, 85)
                .addComponent(jLabel8)
                .addGap(53, 53, 53))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 5));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 35)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 255));
        jLabel12.setText("Login Page");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(149, 149, 149))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12)
        );

        cb.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        cb.setForeground(new java.awt.Color(51, 51, 255));
        cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Admin", "User" }));

        otptb.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        otptb.setForeground(new java.awt.Color(51, 51, 255));
        otptb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otptbActionPerformed(evt);
            }
        });

        otp.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        otp.setForeground(new java.awt.Color(51, 51, 255));
        otp.setText("Captcha");

        pnt1lbl.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        pnt1lbl.setForeground(new java.awt.Color(51, 51, 255));
        pnt1lbl.setText(":");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Password");

        pntlbl.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        pntlbl.setForeground(new java.awt.Color(51, 51, 255));
        pntlbl.setText(":");

        otplbl.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        otplbl.setForeground(new java.awt.Color(51, 51, 255));
        otplbl.setText("mobile number");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText(":");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText(":");

        otpnumlbl.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        otpnumlbl.setForeground(new java.awt.Color(51, 51, 255));
        otpnumlbl.setText("Enter the showing Captcha  ");

        uid.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        uid.setForeground(new java.awt.Color(51, 51, 255));
        uid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uidActionPerformed(evt);
            }
        });
        uid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                uidKeyReleased(evt);
            }
        });

        verifybtn.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        verifybtn.setForeground(new java.awt.Color(51, 51, 255));
        verifybtn.setText("Verify");
        verifybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifybtnActionPerformed(evt);
            }
        });

        pswd.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        pswd.setForeground(new java.awt.Color(51, 51, 255));
        pswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswdActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("User ID");

        loginbtn.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        loginbtn.setForeground(new java.awt.Color(51, 51, 255));
        loginbtn.setText("LOGIN");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });

        resetbtn.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        resetbtn.setForeground(new java.awt.Color(51, 51, 255));
        resetbtn.setText("RESET");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(verifybtn)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel6)
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel5)))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pswd)
                                    .addComponent(uid, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)))
                            .addComponent(otptb, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(109, 109, 109))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(212, 212, 212)
                                .addComponent(resetbtn)
                                .addGap(87, 87, 87)
                                .addComponent(loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(otp)
                                .addGap(58, 58, 58)
                                .addComponent(pntlbl))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(242, 242, 242)
                                .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(otpnumlbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnt1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(otplbl)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uid, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(pswd, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(verifybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnt1lbl)
                    .addComponent(otplbl)
                    .addComponent(otpnumlbl))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(otp)
                    .addComponent(pntlbl)
                    .addComponent(otptb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public static String generateOtp() {
        Random random = new Random();
        StringBuilder sb = new StringBuilder();
        sb.append(random.nextInt(10000000));
        return sb.toString();
    }
    private void uidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uidActionPerformed

    private void verifybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifybtnActionPerformed
        // TODO add your handling code here: 
        String aupass;
        boolean found = false; // Track if login is successful

        String username = uid.getText().trim();
        String password = pswd.getText().trim();

        // 🔹 Step 1: Basic Validation
        if (username.equals("") && password.equals("")) {
            JOptionPane.showMessageDialog(
                    this,
                    new JLabel("<html><span style='color:orange; font-size:14px; font-weight:bold;'>Please enter username and password!</span></html>"),
                    "Missing Fields",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        } else if (username.equals("")) {
            JOptionPane.showMessageDialog(
                    this,
                    new JLabel("<html><span style='color:orange; font-size:14px; font-weight:bold;'>Please enter username!</span></html>"),
                    "Missing Username",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        } else if (password.equals("")) {
            JOptionPane.showMessageDialog(
                    this,
                    new JLabel("<html><span style='color:orange; font-size:14px; font-weight:bold;'>Please enter password!</span></html>"),
                    "Missing Password",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // 🔹 Step 2: Role-based Login Check
        if (cb.getSelectedIndex() == 1) { // Admin Login
            cb.getSelectedIndex();
            auid = username;

            // ✅ Encrypt password (comment out next line if using plain text passwords)
            aupass = encrypt(password);
            // aupass = password; // Uncomment if passwords in DB are NOT encrypted

            boolean foundAdmin = false;

            // ✅ Hardcoded Admin Access
            if (auid.equals("11") && password.equals("1998")) //Admin@password
            {
//            foundAdmin = true;
                JOptionPane.showMessageDialog(
                        this,
                        new JLabel("<html><span style='color:green; font-size:14px; font-weight:bold;'>Successfully Verified (Hardcoded Admin)</span></html>"),
                        "Admin Login",
                        JOptionPane.INFORMATION_MESSAGE
                );

                OTP = generateOtp();
                loginbtn.setVisible(true);
                otpnumlbl.setVisible(true);
                otplbl.setVisible(true);
                pnt1lbl.setVisible(true);
                otptb.setEditable(true);
                otp.setVisible(true);
                pntlbl.setVisible(true);
                loginbtn.setVisible(true);
                otplbl.setText(OTP);
            } else {
                try {
                    Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/shoeshopdb", "root", "");
                    PreparedStatement pt = c.prepareStatement("SELECT * FROM admin");
                    ResultSet rs = pt.executeQuery();

                    while (rs.next()) {
                        if (auid.equals(rs.getString(1)) && aupass.equals(rs.getString(5))) {
                            foundAdmin = true;
                            k = 1;
                            JOptionPane.showMessageDialog(
                                    this,
                                    new JLabel("<html><span style='color:green; font-size:14px; font-weight:bold;'>Successfully Verified Admin ID and Password!</span></html>"),
                                    "Admin Login",
                                    JOptionPane.INFORMATION_MESSAGE
                            );

                            OTP = generateOtp();
                            loginbtn.setVisible(true);
                            otpnumlbl.setVisible(true);
                            otplbl.setVisible(true);
                            pnt1lbl.setVisible(true);
                            otptb.setEditable(true);
                            otp.setVisible(true);
                            pntlbl.setVisible(true);
                            loginbtn.setVisible(true);
                            otplbl.setText(OTP);
                            break;
                        }
                    }

                    if (!foundAdmin) {
                        JOptionPane.showMessageDialog(
                                this,
                                new JLabel("<html><span style='color:red; font-size:14px; font-weight:bold;'>Wrong Admin ID or Password!</span></html>"),
                                "Login Failed",
                                JOptionPane.ERROR_MESSAGE
                        );
                        uid.setText("");
                        pswd.setText("");
                        cb.setSelectedIndex(0);
                    }

                } catch (HeadlessException | SQLException e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            }
        } else if (cb.getSelectedIndex() == 2) { // User Login
            auid = username;

            // ✅ Encrypt password (comment out next line if your DB has plain passwords)
            aupass = encrypt(password);
            // aupass = password; // Uncomment if DB stores plain text passwords

            boolean foundUser = false;

            try {
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/shoeshopdb", "root", "");
                PreparedStatement pt = c.prepareStatement("SELECT * FROM users");
                ResultSet rs = pt.executeQuery();

                while (rs.next()) {
                    if (auid.equals(rs.getString(1)) && aupass.equals(rs.getString(6))) {
                        foundUser = true;
                        k = 1;
                        JOptionPane.showMessageDialog(
                                this,
                                new JLabel("<html><span style='color:green; font-size:14px; font-weight:bold;'>Successfully Verified User ID and Password!</span></html>"),
                                "User Login",
                                JOptionPane.INFORMATION_MESSAGE
                        );

                        OTP = generateOtp();
                        loginbtn.setVisible(true);
                        otpnumlbl.setVisible(true);
                        otplbl.setVisible(true);
                        pnt1lbl.setVisible(true);
                        otptb.setEditable(true);
                        otp.setVisible(true);
                        pntlbl.setVisible(true);
                        loginbtn.setVisible(true);
                        otplbl.setText(OTP);
                        break;
                    }
                }

                if (!foundUser) {
                    JOptionPane.showMessageDialog(
                            this,
                            new JLabel("<html><span style='color:red; font-size:14px; font-weight:bold;'>Wrong User ID or Password!</span></html>"),
                            "Login Failed",
                            JOptionPane.ERROR_MESSAGE
                    );
                    uid.setText("");
                    pswd.setText("");
                    cb.setSelectedIndex(0);
                }

            } catch (HeadlessException | SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        } else { // No Role Selected
            JOptionPane.showMessageDialog(
                    this,
                    new JLabel("<html><span style='color:orange; font-size:14px; font-weight:bold;'>Select Appropriate Role!</span></html>"),
                    "Missing Role",
                    JOptionPane.WARNING_MESSAGE
            );

            cb.setSelectedIndex(0);
            uid.setText("");
            pswd.setText("");
            otplbl.setText("");
            otpnumlbl.setText("");
            pnt1lbl.setText("");
            loginbtn.setVisible(false);
            otptb.setEditable(false);
            otptb.setText("");
        }
    }//GEN-LAST:event_verifybtnActionPerformed

    private void pswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswdActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here:
        String enteredOTP = otptb.getText().trim();

        // Step 1: Validate OTP field first
        if (enteredOTP.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    new JLabel("<html><span style='color:orange; font-size:14px; font-weight:bold;'>Please enter the OTP!</span></html>"),
                    "Missing OTP",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // Step 2: Determine selected role
        int selectedindex = cb.getSelectedIndex();

        // Step 3: If admin selected
        if (selectedindex == 1) {
            if (k == 1) {
                // Admin verified from DB
                if (enteredOTP.equals(OTP)) {
                    new Questions(auid, selectedindex).setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(
                            this,
                            new JLabel("<html><span style='color:red; font-size:14px; font-weight:bold;'>Incorrect OTP! Please try again.</span></html>"),
                            "OTP Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                }
            } else {
                // Hardcoded Admin
                if (enteredOTP.equals(OTP)) {
                    new AdDash1("0").setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(
                            this,
                            new JLabel("<html><span style='color:red; font-size:14px; font-weight:bold;'>Incorrect OTP! Please try again.</span></html>"),
                            "OTP Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                }
            }
        } // Step 4: If user selected
        else if (selectedindex == 2) {
            if (k == 1) { // ✅ User verified from DB
                if (enteredOTP.equals(OTP)) {
                    new Questions(auid, selectedindex).setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(
                            this,
                            new JLabel("<html><span style='color:red; font-size:14px; font-weight:bold;'>Incorrect OTP! Please try again.</span></html>"),
                            "OTP Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                }
            } else {
                JOptionPane.showMessageDialog(
                        this,
                        new JLabel("<html><span style='color:red; font-size:14px; font-weight:bold;'>Please verify username and password first!</span></html>"),
                        "Login Failed",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        } // Step 5: If no role selected
        else {
            JOptionPane.showMessageDialog(
                    this,
                    new JLabel("<html><span style='color:orange; font-size:14px; font-weight:bold;'>Please select a role first!</span></html>"),
                    "Missing Role",
                    JOptionPane.WARNING_MESSAGE
            );
            cb.setSelectedIndex(0);
            uid.setText("");
            pswd.setText("");
            otptb.setText("");
            otplbl.setText("");
            otpnumlbl.setText("");
            pnt1lbl.setText("");
            loginbtn.setVisible(false);
            otptb.setEditable(false);
        }
    }//GEN-LAST:event_loginbtnActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        // TODO add your handling code here:
        cb.setSelectedIndex(0);
        uid.setText("");
        pswd.setText("");
        otplbl.setText("");
        otpnumlbl.setText("");
        pnt1lbl.setText("");
        loginbtn.setVisible(false);
        otptb.setEditable(false);
        otptb.setText("");
    }//GEN-LAST:event_resetbtnActionPerformed

    private void uidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uidKeyReleased
        // TODO add your handling code here:
        if (!uid.getText().matches("\\d*\\.?\\d*")) {
            JOptionPane.showMessageDialog(this, "Please enter only numeric values!");
            // Remove the last typed character
            if (uid.getText().length() > 0) {
                uid.setText("");
            }
            return;
        }
    }//GEN-LAST:event_uidKeyReleased

    private void otptbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otptbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otptbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginbtn;
    private javax.swing.JLabel otp;
    private javax.swing.JLabel otplbl;
    private javax.swing.JLabel otpnumlbl;
    private javax.swing.JTextField otptb;
    private javax.swing.JLabel pnt1lbl;
    private javax.swing.JLabel pntlbl;
    private javax.swing.JPasswordField pswd;
    private javax.swing.JButton resetbtn;
    private javax.swing.JTextField uid;
    private javax.swing.JButton verifybtn;
    // End of variables declaration//GEN-END:variables
}
