/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package shoeshopmng;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Timestamp;
import javax.swing.JOptionPane;

/**
 *
 * @author hdoff
 */
public class SetQuestion extends javax.swing.JFrame {

    /** Creates new form SetQuestion */
    String aid;
    String uid;
    String uname;
    String aname;
    String uaddress;
    String aaddress;
    String ucontact;
    String acontact;
    String udoj;
    String upass;
    String apass;
    String eaid;
    String previousauid;
//    String euid;
//    String username;
    String adminname;
    int k;
    int flag;
    public SetQuestion() {
        initComponents();
    }
     public SetQuestion(String id,String name,String address,String contact,String doj,String pass,String auid, String previousid,int flg) {
        initComponents();
        uid=id;
        k=1;
        uname=name;
       uaddress=address;
        ucontact=contact;
        upass=pass;
        udoj=doj;
        eaid = auid;
        flag = flg;
        try {
           
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/shoeshopdb","root","");
            PreparedStatement pt2=c.prepareStatement("select name from admin where id = ?");
            pt2.setString(1, eaid);
            ResultSet rs2 = pt2.executeQuery();
            if (rs2.next()) 
            {
              adminname = rs2.getString("name");
            }
            if(auid.equals("0"))
            {
                adminname = "Super Admin";
            }
            if(flag == 0)
            {
            saveupdatebtn.setText("Update");
            }
            c.close();
            Connection c1=DriverManager.getConnection("jdbc:mysql://localhost:3306/shoeshopdb","root","");
            PreparedStatement pt3=c1.prepareStatement("select pet,school from users where id = ?");
            if(!previousid.equals("0"))
            {
               previousauid = previousid;
               pt3.setString(1, previousauid);
            }
            else
            {
             pt3.setString(1, uid);   
            }
            ResultSet rs3 = pt3.executeQuery();
            if (rs3.next()) 
            {
              pettb.setText(rs3.getString("pet"));
              schltb.setText(rs3.getString("School"));
            }
        }
        catch(Exception e)
        {
            
        }
    }
     public SetQuestion(String id,String name,String address,String contact, String pass, String auid, String previousid, int flg) {
        initComponents();
        aid=id;
        k=2;
        aname=name;
        aaddress=address;
        acontact=contact;
        apass=pass;
        eaid = auid;
        flag = flg;
        try {
           
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/shoeshopdb","root","");
            PreparedStatement pt2=c.prepareStatement("select name from admin where id = ?");
            pt2.setString(1, eaid);
            ResultSet rs2 = pt2.executeQuery();
            if (rs2.next()) 
            {
              adminname = rs2.getString("name");
            }
            if(auid.equals("0"))
            {
                adminname = "Super Admin";
            }
            if(flag == 0)
            {
            saveupdatebtn.setText("Update");
            }
            c.close();
            Connection c1=DriverManager.getConnection("jdbc:mysql://localhost:3306/shoeshopdb","root","");
            PreparedStatement pt3=c1.prepareStatement("select pet,school from admin where id = ?");
            if(!previousid.equals("0"))
            {
               previousauid = previousid;
               pt3.setString(1, previousauid);
            }
            else
            {
                 pt3.setString(1, aid);
            }
            ResultSet rs3 = pt3.executeQuery();
            if (rs3.next()) 
            {
              pettb.setText(rs3.getString("pet"));
              schltb.setText(rs3.getString("School"));
            }
        }
        catch(Exception e)
        {
            
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveupdatebtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pettb = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        schltb = new javax.swing.JTextField();
        backbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        saveupdatebtn.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        saveupdatebtn.setForeground(new java.awt.Color(51, 51, 255));
        saveupdatebtn.setText("Save");
        saveupdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveupdatebtnActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 5));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("Trust Worthy");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("Stock");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 255));
        jLabel14.setText("Quality");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 255));
        jLabel15.setText("3 layer security");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel9)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel10)
                .addGap(106, 106, 106)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(91, 91, 91)
                .addComponent(jLabel15)
                .addGap(39, 39, 39))
        );

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 255));
        jLabel16.setText("Enter your first school name : ");

        pettb.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        pettb.setForeground(new java.awt.Color(51, 51, 255));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 255));
        jLabel17.setText("Enter your first pet name : ");

        schltb.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        schltb.setForeground(new java.awt.Color(51, 51, 255));

        backbtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        backbtn.setForeground(new java.awt.Color(0, 51, 255));
        backbtn.setText("BACK");
        backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbtnMouseClicked(evt);
            }
        });
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 5));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 35)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Security Questions");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel8)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pettb, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(schltb, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveupdatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pettb, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(schltb, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveupdatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveupdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveupdatebtnActionPerformed
        // TODO add your handling code here:
        if(k == 1 && flag == 1)
        {
          try
        {
            saveupdatebtn.setText("Save");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/shoeshopdb","root","");
            PreparedStatement pst = c.prepareStatement("INSERT INTO users (id, name, address, contact, doj, password, pet, school, created_at, created_by) " + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
            pst.setString(1,uid);
            pst.setString(2, uname);
            pst.setString(3,uaddress);
            pst.setString(4,ucontact);
            pst.setString(5,udoj);
            pst.setString(6,upass);
            pst.setString(7, pettb.getText());
            pst.setString(8,schltb.getText());
            pst.setTimestamp(9, Timestamp.valueOf(java.time.LocalDateTime.now()));
            pst.setString(10, adminname);
//            pst.setTimestamp(11, Timestamp.valueOf(java.time.LocalDateTime.now()));
//            pst.setString(12, adminname);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"New User's Data added");
            new Users(eaid).setVisible(true);
            this.dispose();
        }
        catch(Exception e)
        {

        }  
        }
        else if(k==2 && flag == 1)
        {
            try
        {
            saveupdatebtn.setText("Save");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/shoeshopdb","root","");
                     PreparedStatement pst = c.prepareStatement("INSERT INTO admin (id, name, address, contact, password, pet, school, created_at, created_by) " + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)");
                     pst.setString(1,aid);
                     pst.setString(2, aname);
                     pst.setString(3,aaddress);
                     pst.setString(4,acontact);
                     pst.setString(5,apass);
                     pst.setString(6, pettb.getText());
                     pst.setString(7,schltb.getText());
                     pst.setTimestamp(8, Timestamp.valueOf(java.time.LocalDateTime.now()));
                     pst.setString(9, adminname);
//                     pst.setTimestamp(11, Timestamp.valueOf(java.time.LocalDateTime.now()));
//                     pst.setString(12, adminname);
                     pst.executeUpdate(); 
                     JOptionPane.showMessageDialog(this,"Data added");
                     new Admin(eaid).setVisible(true);
                     this.dispose();
        }
        catch(Exception e)
        {

        }
        }
        else if(k == 1 && flag == 0)
        {
          String petname = pettb.getText();
          String schoolname = schltb.getText();
          try
          {
                Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/shoeshopdb","root","");
                PreparedStatement pst=c.prepareStatement("update users set id='"+uid+"',name='"+uname+"',address='"+uaddress+"',contact='"+ucontact+"', doj = '"+udoj+"', password='"+upass+"',pet = '"+petname+"', school = '"+schoolname+"', updated_at = '"+Timestamp.valueOf(java.time.LocalDateTime.now())+"', updated_by = '"+adminname+"' where id='"+previousauid+"'");
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"User's Data Updated Successfully");
                new Users(eaid).setVisible(true);
                this.dispose();
          }
          catch(Exception e)
          {
              JOptionPane.showMessageDialog(this, e, "Warning", JOptionPane.WARNING_MESSAGE);
          }
        }
        else if(k == 2 && flag == 0) {
    String petname = pettb.getText();
    String schoolname = schltb.getText();
    try {
        Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/shoeshopdb","root","");
        
        String sql = "UPDATE admin SET id=?, name=?, address=?, contact=?, password=?, pet=?, school=?, updated_at=?, updated_by=? WHERE id=?";
        PreparedStatement pst = c.prepareStatement(sql);
        
        pst.setString(1, aid);
        pst.setString(2, aname);
        pst.setString(3, aaddress);
        pst.setString(4, acontact);
        pst.setString(5, apass);
        pst.setString(6, petname);
        pst.setString(7, schoolname);
        pst.setTimestamp(8, Timestamp.valueOf(java.time.LocalDateTime.now()));
        pst.setString(9, adminname);
        pst.setString(10, previousauid); // this must be the old ID

        int rows = pst.executeUpdate();
        if(rows > 0) {
            JOptionPane.showMessageDialog(this,"Admin's Data Updated Successfully");
            new Admin(eaid).setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this,"No record found to update","Warning",JOptionPane.WARNING_MESSAGE);
        }
    } catch(Exception e) {
        JOptionPane.showMessageDialog(this, e, "Warning", JOptionPane.WARNING_MESSAGE);
    }
    }
    }//GEN-LAST:event_saveupdatebtnActionPerformed

    private void backbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseClicked
        // TODO add your handling code here:
        new Admin(eaid).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbtnMouseClicked

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        new Admin(eaid).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField pettb;
    private javax.swing.JButton saveupdatebtn;
    private javax.swing.JTextField schltb;
    // End of variables declaration//GEN-END:variables

}
