/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shoeshopmng;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author hdoff
 */
public class Stocks extends javax.swing.JFrame {

    /**
     * Creates new form Stocks
     */
    long sid;
    String auid;
    String adminname;
    public Stocks() {
        initComponents();
    }    
        
    public Stocks(String auid) {
        initComponents();
        try {
            DefaultTableModel model= (DefaultTableModel) shoetbl.getModel();
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/shoeshopdb","root","");
            PreparedStatement pt=c.prepareStatement("select * from shoes");
            ResultSet rs=pt.executeQuery();
            while(rs.next())
            {
                model.addRow(new String[] {rs.getString(1),rs.getString(2),
                rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)+"%",
                rs.getString(7), rs.getString(8), rs.getString(9), rs.getString(10)});
            }
            this.auid = auid;
            PreparedStatement pt2=c.prepareStatement("select name from admin where id = ?");
            pt2.setString(1, this.auid);
            ResultSet rs2 = pt2.executeQuery();
            if (rs2.next()) 
            {
              adminname = rs2.getString("name");
            }
            if(auid.equals(0))
            {
                adminname = "Super Admin";      
            }
        } 
        catch (SQLException ex) {
            //Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        updatebtn.setVisible(false);
         SearchFilter();
    }
 
    
    void SearchFilter()
    {
        DefaultTableModel model = (DefaultTableModel) shoetbl.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        shoetbl.setRowSorter(sorter);

        searchtb.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        public void insertUpdate(javax.swing.event.DocumentEvent e) { search(); }
        public void removeUpdate(javax.swing.event.DocumentEvent e) { search(); }
        public void changedUpdate(javax.swing.event.DocumentEvent e) { search(); }

        private void search() {
        String text = searchtb.getText();
        if (text.trim().length() == 0) {
            sorter.setRowFilter(null); // show all rows if search box is empty
        } else {
            // filter rows based on any column containing the text
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
        }
        }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        deletebtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        resetbtn = new javax.swing.JButton();
        sbrandtb = new javax.swing.JTextField();
        updatebtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        stypecb = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        spricetb = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        searchtb = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        shoetbl = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        quantitytb = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        DiscountTb = new javax.swing.JTextField();
        sidtb = new javax.swing.JTextField();

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 5));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Inventory");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(465, 465, 465)
                .addComponent(jLabel8)
                .addContainerGap(499, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        deletebtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        deletebtn.setForeground(new java.awt.Color(0, 51, 255));
        deletebtn.setText("DELETE");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 255));
        jLabel17.setText("Brand");

        resetbtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        resetbtn.setForeground(new java.awt.Color(0, 51, 255));
        resetbtn.setText("RESET");
        resetbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetbtnMouseClicked(evt);
            }
        });
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });

        sbrandtb.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        sbrandtb.setForeground(new java.awt.Color(51, 51, 255));
        sbrandtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbrandtbActionPerformed(evt);
            }
        });

        updatebtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        updatebtn.setForeground(new java.awt.Color(0, 51, 255));
        updatebtn.setText("UPDATE");
        updatebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatebtnMouseClicked(evt);
            }
        });
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        savebtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        savebtn.setForeground(new java.awt.Color(0, 51, 255));
        savebtn.setText("SAVE");
        savebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savebtnMouseClicked(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 255));
        jLabel21.setText("Stocks");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 255));
        jLabel19.setText("Type");

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 51, 255));
        jButton5.setText("BACK");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        stypecb.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        stypecb.setForeground(new java.awt.Color(51, 51, 255));
        stypecb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Sleeper", "Sports ", "Sneakers", "Sandals", "Formals", "Football Shoes", "Casuals", "Jootis", "Valley", "Boots", "Cycling Shoes", "Baby Shoes", "Baby Sandals", "Baby Sleepers", "Baby Crooks", "Crooks ", "Women Sandals", "Women's High Heels", "Women's Jootis", "Women Sleepers" }));

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 51, 255));
        jButton6.setText("Exit");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 255));
        jLabel20.setText("Price");

        spricetb.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        spricetb.setForeground(new java.awt.Color(51, 51, 255));
        spricetb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spricetbActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 255));
        jLabel16.setText("Shoe Id");

        searchtb.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        searchtb.setForeground(new java.awt.Color(51, 51, 255));
        searchtb.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtbActionPerformed(evt);
            }
        });
        searchtb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchtbKeyReleased(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 8));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("Stock");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("Trust Worthy");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 255));
        jLabel11.setText("Multi Admin");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 255));
        jLabel12.setText("Effective Cost");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 255));
        jLabel13.setText("Multi User");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 255));
        jLabel14.setText("Quality");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(45, 45, 45)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addGap(14, 14, 14)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel10)
                .addGap(84, 84, 84)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(93, 93, 93)
                .addComponent(jLabel14)
                .addGap(84, 84, 84)
                .addComponent(jLabel11)
                .addGap(77, 77, 77)
                .addComponent(jLabel12)
                .addGap(51, 51, 51))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 5));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 255));
        jLabel23.setText("Inventory");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(465, 465, 465)
                .addComponent(jLabel23)
                .addContainerGap(610, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel23)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        shoetbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0), 2));
        shoetbl.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        shoetbl.setForeground(new java.awt.Color(51, 51, 255));
        shoetbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Brand", "Category", "Quantity", "Price", "Discount %", "Created At", "Created By", "Updated At", "Updated By"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        shoetbl.setRowHeight(35);
        shoetbl.setRowMargin(1);
        shoetbl.setSelectionBackground(new java.awt.Color(255, 255, 0));
        shoetbl.setSelectionForeground(new java.awt.Color(51, 51, 255));
        shoetbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shoetblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(shoetbl);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 255));
        jLabel22.setText("Quantity");

        quantitytb.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        quantitytb.setForeground(new java.awt.Color(51, 51, 255));
        quantitytb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantitytbActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 255));
        jLabel24.setText("Discount %");

        DiscountTb.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        DiscountTb.setForeground(new java.awt.Color(51, 51, 255));
        DiscountTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiscountTbActionPerformed(evt);
            }
        });
        DiscountTb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DiscountTbKeyReleased(evt);
            }
        });

        sidtb.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        sidtb.setForeground(new java.awt.Color(51, 51, 255));
        sidtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidtbActionPerformed(evt);
            }
        });
        sidtb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sidtbKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchtb, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(414, 414, 414)
                                .addComponent(jLabel21)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(sidtb, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(sbrandtb, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(stypecb, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel22)
                                            .addComponent(quantitytb, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addComponent(spricetb, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel24)
                                            .addComponent(DiscountTb, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(32, 32, 32))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(714, 714, 714)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sidtb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spricetb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel22)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(quantitytb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(stypecb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sbrandtb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DiscountTb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
    DefaultTableModel model = (DefaultTableModel) shoetbl.getModel();
    int selectedRow = shoetbl.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a row to delete!", "Alert", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Get ID from the selected row
    String id = model.getValueAt(selectedRow, 0).toString();

    int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete this Item?","Confirm Delete",JOptionPane.YES_NO_OPTION);

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    try {
        Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/shoeshopdb", "root", "");
        PreparedStatement pst = c.prepareStatement("DELETE FROM shoes WHERE id=?");
        pst.setString(1, id);
        pst.executeUpdate();

        // Remove row from JTable
        model.removeRow(selectedRow);

        JOptionPane.showMessageDialog(this, "Data Deleted Successfully");

        // Reset fields
        sidtb.setText("");
        sbrandtb.setText("");
        stypecb.setSelectedIndex(0);
        spricetb.setText("");  
        quantitytb.setText("");
        DiscountTb.setText("");
        savebtn.setVisible(true);
        updatebtn.setVisible(false);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error deleting record: " + e.getMessage());
    }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void resetbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetbtnMouseClicked
        sidtb.setText("");
        sbrandtb.setText("");
        stypecb.setSelectedIndex(0);
        spricetb.setText("");
        quantitytb.setText("");
        DiscountTb.setText("");
        savebtn.setVisible(true);
        updatebtn.setVisible(false);
    }//GEN-LAST:event_resetbtnMouseClicked

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetbtnActionPerformed

    private void sbrandtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbrandtbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sbrandtbActionPerformed

    private void updatebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatebtnMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)shoetbl.getModel();
        if(sidtb.getText().equals("") || sbrandtb.getText().equals("") ||  stypecb.getSelectedIndex()==0 || spricetb.getText().equals("") || quantitytb.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Enter all Values","Alert",JOptionPane.WARNING_MESSAGE);
        }
        else if(shoetbl.getSelectedRowCount()==1)
             {
                 Long id=Long.valueOf(sidtb.getText());
                 String brand=sbrandtb.getText();
                 String type=stypecb.getSelectedItem().toString();
                 Double price=Double.valueOf(spricetb.getText());
                 Double quant=Double.valueOf(quantitytb.getText());
                 Double discount;
                 if(!DiscountTb.getText().isEmpty() || !DiscountTb.getText().equals(""))
                 {
                  discount = Double.valueOf(DiscountTb.getText());
                 }
                 else
                 {
                     discount = Double.valueOf(0);
                 }
             try
             {
                 
                 Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/shoeshopdb","root","");
                 PreparedStatement pst=c.prepareStatement("update shoes set id='"+id+"',brand='"+brand+"',category='"+type+"',quantity='"+quant+"',price='"+price+"',discount ='"+discount+"', updated_at = '"+Timestamp.valueOf(java.time.LocalDateTime.now())+"', updated_by = '"+adminname+"' where id='"+sid+"'");
                 pst.executeUpdate();
                 JOptionPane.showMessageDialog(this,"Data Updated Successfully");
                 model.setValueAt(id,shoetbl.getSelectedRow(),0);
                 model.setValueAt(brand,shoetbl.getSelectedRow(),1);
                 model.setValueAt(type,shoetbl.getSelectedRow(),2);
                 model.setValueAt(quant,shoetbl.getSelectedRow(),3);
                 model.setValueAt(price,shoetbl.getSelectedRow(),4);
                 model.setValueAt(discount + "%",shoetbl.getSelectedRow(),5);
                 model.setValueAt(Timestamp.valueOf(java.time.LocalDateTime.now()) ,shoetbl.getSelectedRow(),8);
                 model.setValueAt(adminname, shoetbl.getSelectedRow(), 9);
                    sidtb.setText("");
                    sbrandtb.setText("");
                    stypecb.setSelectedIndex(0);
                    spricetb.setText("");  
                    quantitytb.setText("");
                    DiscountTb.setText("");
                        savebtn.setVisible(true);
                  updatebtn.setVisible(false);
             }
             catch(Exception e)
             {
                 
             }
             }
    }//GEN-LAST:event_updatebtnMouseClicked

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatebtnActionPerformed

    private void savebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savebtnMouseClicked
        // TODO add your handling code here:
       DefaultTableModel tblmodel = (DefaultTableModel) shoetbl.getModel();
       Timestamp todaydatetime = Timestamp.valueOf(java.time.LocalDateTime.now());

if (stypecb.getSelectedIndex() == 0 || 
    sidtb.getText().equals("") || 
    sbrandtb.getText().equals("") || 
    spricetb.getText().equals("") || 
    quantitytb.getText().equals("")) {
    
    JOptionPane.showMessageDialog(this, "Please enter all values", "Alert", JOptionPane.WARNING_MESSAGE);
} 
else {
    try {
        double discount;
        if (!DiscountTb.getText().isEmpty()) {
            discount = Double.parseDouble(DiscountTb.getText());
        } else {
            discount = 0;
        }

        // ✅ Connect and Insert
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/shoeshopdb", "root", "");
        PreparedStatement pst = con.prepareStatement("insert into shoes(id,brand,category,quantity,price,discount,created_at,created_by)" + "Values(?,?,?,?,?,?,?,?)");
        
        pst.setLong(1, Long.parseLong(sidtb.getText()));
        pst.setString(2, sbrandtb.getText());
        pst.setString(3, stypecb.getSelectedItem().toString());
        pst.setDouble(4, Double.parseDouble(quantitytb.getText()));
        pst.setDouble(5, Double.parseDouble(spricetb.getText()));
        pst.setDouble(6, discount);
        pst.setString(7, todaydatetime.toString());
        pst.setString(8, adminname);
//        pst.setString(9, todaydatetime.toString());
//        pst.setString(10, adminname);
        
        int rows = pst.executeUpdate();
        
        if (rows > 0) {
            // ✅ Add to table *before* clearing text fields
            tblmodel.addRow(new Object[]{
                sidtb.getText(),
                sbrandtb.getText(),
                stypecb.getSelectedItem(),
                quantitytb.getText(),
                spricetb.getText(),
                discount + "%",
                todaydatetime,
                adminname
//                todaydatetime,
//                adminname
            });
            
            JOptionPane.showMessageDialog(this, "New Shoes Stock Added");
        }
        
        // ✅ Clear fields *after* adding row
        sidtb.setText("");
        sbrandtb.setText("");
        stypecb.setSelectedIndex(0);
        spricetb.setText("");
        quantitytb.setText("");
        DiscountTb.setText("");
        pst.close();
        con.close();
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}
    }//GEN-LAST:event_savebtnMouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        new AdDash1(auid).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        new Login1().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void spricetbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spricetbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spricetbActionPerformed

    private void searchtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchtbActionPerformed

    private void quantitytbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantitytbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantitytbActionPerformed

    private void shoetblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shoetblMouseClicked
        // TODO add your handling code here:
        savebtn.setVisible(false);
        updatebtn.setVisible(true);
        DefaultTableModel tblmdl=(DefaultTableModel)shoetbl.getModel();
        int selectedrowindex=shoetbl.getSelectedRow();
        sid=Long.parseLong(tblmdl.getValueAt(selectedrowindex,0).toString());
        sidtb.setText(tblmdl.getValueAt(selectedrowindex,0).toString());
        sbrandtb.setText(tblmdl.getValueAt(selectedrowindex,1).toString());
        stypecb.setSelectedItem(tblmdl.getValueAt(selectedrowindex,2).toString());
        quantitytb.setText(tblmdl.getValueAt(selectedrowindex,3).toString());
        spricetb.setText(tblmdl.getValueAt(selectedrowindex,4).toString());
        DiscountTb.setText(tblmdl.getValueAt(selectedrowindex,5).toString().replace("%",""));
        if(tblmdl.getRowCount()==0)
        {
            savebtn.setVisible(true);
        }
    }//GEN-LAST:event_shoetblMouseClicked

    private void DiscountTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscountTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiscountTbActionPerformed

    private void DiscountTbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DiscountTbKeyReleased
        // TODO add your handling code here:
        String text = DiscountTb.getText().trim();

    // Allow empty input or valid decimal numbers
    if (!text.isEmpty() && !text.matches("\\d*(\\.\\d{0,2})?")) {
        JOptionPane.showMessageDialog(this, "Please enter only numeric values (e.g., 5 or 4.5)");
        DiscountTb.setText("");  // clear invalid input
    }
    }//GEN-LAST:event_DiscountTbKeyReleased

    private void searchtbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtbKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_searchtbKeyReleased

    private void sidtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidtbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sidtbActionPerformed

    private void sidtbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sidtbKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sidtbKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stocks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stocks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DiscountTb;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField quantitytb;
    private javax.swing.JButton resetbtn;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField sbrandtb;
    private javax.swing.JTextField searchtb;
    private javax.swing.JTable shoetbl;
    private javax.swing.JTextField sidtb;
    private javax.swing.JTextField spricetb;
    private javax.swing.JComboBox<String> stypecb;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
